/**
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Broker } from './broker';

import ApiClient from "../ApiClient";

export class BrokersProgramInfo { 
    public brokers?: [Broker];
    public currentAccountTypeId?: string;

    static constructFromObject(data: {[key: string]: any}, obj: BrokersProgramInfo = new BrokersProgramInfo()): BrokersProgramInfo {
        if (data) {
            if (data.hasOwnProperty('brokers')) {
                obj['brokers'] = ApiClient.convertToType(data['brokers'], [Broker]);
            }
            if (data.hasOwnProperty('currentAccountTypeId')) {
                obj['currentAccountTypeId'] = ApiClient.convertToType(data['currentAccountTypeId'], 'string');
            }
        }
        return obj;
    }
}




