/**
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DashboardAsset } from './dashboardAsset';

import ApiClient from "../ApiClient";

export class DashboardAssets { 
    public assets?: [DashboardAsset];
    public othersPercent?: number;

    static constructFromObject(data: {[key: string]: any}, obj: DashboardAssets = new DashboardAssets()): DashboardAssets {
        if (data) {
            if (data.hasOwnProperty('assets')) {
                obj['assets'] = ApiClient.convertToType(data['assets'], [DashboardAsset]);
            }
            if (data.hasOwnProperty('othersPercent')) {
                obj['othersPercent'] = ApiClient.convertToType(data['othersPercent'], 'number');
            }
        }
        return obj;
    }
}




