/**
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventFilters } from './EventFilters';
import { FilterItemInfo } from './FilterItemInfo';

import ApiClient from "../ApiClient";

export class FilterInfo { 
    public 'walletTransactions': Array<FilterItemInfo>;
    public 'walletExternalTransactions': Array<FilterItemInfo>;
    public 'events': EventFilters;
    public 'assets': Array<FilterItemInfo>;

    constructor(data: {[key: string]: any}) { 
        this['walletTransactions'] = data['walletTransactions'];
        this['walletExternalTransactions'] = data['walletExternalTransactions'];
        this['events'] = data['events'];
        this['assets'] = data['assets'];
    }

    static constructFromObject(data: {[key: string]: any}): FilterInfo | undefined {
        if (data) {
            return new FilterInfo({ 
                'walletTransactions': ApiClient.convertToType(data['walletTransactions'], [FilterItemInfo]),
                'walletExternalTransactions': ApiClient.convertToType(data['walletExternalTransactions'], [FilterItemInfo]),
                'events': EventFilters.constructFromObject(data['events']),
                'assets': ApiClient.convertToType(data['assets'], [FilterItemInfo]),
            });
        }
    }
}



