/**
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaptchaCheckResult } from './CaptchaCheckResult';

import ApiClient from "../ApiClient";

export class ForgotPasswordViewModel { 
    public 'email': string;
    public 'captchaCheckResult': CaptchaCheckResult;

    constructor(data: {[key: string]: any}) { 
        this['email'] = data['email'];
        this['captchaCheckResult'] = data['captchaCheckResult'];
    }

    static constructFromObject(data: {[key: string]: any}): ForgotPasswordViewModel | undefined {
        if (data) {
            return new ForgotPasswordViewModel({ 
                'email': ApiClient.convertToType(data['email'], 'string'),
                'captchaCheckResult': CaptchaCheckResult.constructFromObject(data['captchaCheckResult']),
            });
        }
    }
}



