/**
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";

export class GeeTestDetails { 

    constructor(data: {[key: string]: any}) { 
    }

    static constructFromObject(data: {[key: string]: any}): GeeTestDetails | undefined {
        if (data) {
            return new GeeTestDetails({ 
            });
        }
    }
}



