/**
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssetInvestmentRequest } from './AssetInvestmentRequest';

import ApiClient from "../ApiClient";

export class ItemsViewModelAssetInvestmentRequest { 
    public 'items': Array<AssetInvestmentRequest>;
    public 'total': number;

    constructor(data: {[key: string]: any}) { 
        this['items'] = data['items'];
        this['total'] = data['total'];
    }

    static constructFromObject(data: {[key: string]: any}): ItemsViewModelAssetInvestmentRequest | undefined {
        if (data) {
            return new ItemsViewModelAssetInvestmentRequest({ 
                'items': ApiClient.convertToType(data['items'], [AssetInvestmentRequest]),
                'total': ApiClient.convertToType(data['total'], 'number'),
            });
        }
    }
}



