/**
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";

export class LevelsParamsInfo { 
    public 'minAvailableToInvest'?: number;
    public 'maxAvailableToInvest'?: number;
    public 'unverifiedAvailableToInvest'?: number;
    public 'genesisRatioMin'?: number;
    public 'genesisRatioMax'?: number;
    public 'genesisRatioHighRisk'?: number;
    public 'volumeScaleMin'?: number;
    public 'volumeScaleMax'?: number;
    public 'programAgeMax'?: number;
    public 'ageByVolumeMax'?: number;
    public 'investmentScaleMin'?: number;
    public 'investmentScaleMax'?: number;
    public 'investmentScaleHighRisk'?: number;
    constructor() {
    }

    static constructFromObject(data: {[key: string]: any}, obj: LevelsParamsInfo = new LevelsParamsInfo()): LevelsParamsInfo {
        if (data) {
            if (data.hasOwnProperty('minAvailableToInvest')) {
                obj['minAvailableToInvest'] = ApiClient.convertToType(data['minAvailableToInvest'], 'number');
            }
            if (data.hasOwnProperty('maxAvailableToInvest')) {
                obj['maxAvailableToInvest'] = ApiClient.convertToType(data['maxAvailableToInvest'], 'number');
            }
            if (data.hasOwnProperty('unverifiedAvailableToInvest')) {
                obj['unverifiedAvailableToInvest'] = ApiClient.convertToType(data['unverifiedAvailableToInvest'], 'number');
            }
            if (data.hasOwnProperty('genesisRatioMin')) {
                obj['genesisRatioMin'] = ApiClient.convertToType(data['genesisRatioMin'], 'number');
            }
            if (data.hasOwnProperty('genesisRatioMax')) {
                obj['genesisRatioMax'] = ApiClient.convertToType(data['genesisRatioMax'], 'number');
            }
            if (data.hasOwnProperty('genesisRatioHighRisk')) {
                obj['genesisRatioHighRisk'] = ApiClient.convertToType(data['genesisRatioHighRisk'], 'number');
            }
            if (data.hasOwnProperty('volumeScaleMin')) {
                obj['volumeScaleMin'] = ApiClient.convertToType(data['volumeScaleMin'], 'number');
            }
            if (data.hasOwnProperty('volumeScaleMax')) {
                obj['volumeScaleMax'] = ApiClient.convertToType(data['volumeScaleMax'], 'number');
            }
            if (data.hasOwnProperty('programAgeMax')) {
                obj['programAgeMax'] = ApiClient.convertToType(data['programAgeMax'], 'number');
            }
            if (data.hasOwnProperty('ageByVolumeMax')) {
                obj['ageByVolumeMax'] = ApiClient.convertToType(data['ageByVolumeMax'], 'number');
            }
            if (data.hasOwnProperty('investmentScaleMin')) {
                obj['investmentScaleMin'] = ApiClient.convertToType(data['investmentScaleMin'], 'number');
            }
            if (data.hasOwnProperty('investmentScaleMax')) {
                obj['investmentScaleMax'] = ApiClient.convertToType(data['investmentScaleMax'], 'number');
            }
            if (data.hasOwnProperty('investmentScaleHighRisk')) {
                obj['investmentScaleHighRisk'] = ApiClient.convertToType(data['investmentScaleHighRisk'], 'number');
            }
        }
        return obj;
    }
}


//modelGenericEnums.mustache


