/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BrokerOld } from './brokerOld';

import ApiClient from "../ApiClient";

export class MigrationRequestOld { 
    public 'dateCreate'?: Date;
    public 'newLeverage'?: number;
    public 'newBroker'?: BrokerOld;
    constructor() {
    }

    static constructFromObject(data: {[key: string]: any}, obj: MigrationRequestOld = new MigrationRequestOld()): MigrationRequestOld {
        if (data) {
            if (data.hasOwnProperty('dateCreate')) {
                obj['dateCreate'] = ApiClient.convertToType(data['dateCreate'], 'Date');
            }
            if (data.hasOwnProperty('newLeverage')) {
                obj['newLeverage'] = ApiClient.convertToType(data['newLeverage'], 'number');
            }
            if (data.hasOwnProperty('newBroker')) {
                obj['newBroker'] = BrokerOld.constructFromObject(data['newBroker']);
            }
        }
        return obj;
    }
}


//modelGenericEnums.mustache


