/**
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BrokerDetails } from './BrokerDetails';
import { PrivateTradingAccountFullPublicDetails } from './PrivateTradingAccountFullPublicDetails';
import { PrivateTradingAccountFullTradingAccountDetails } from './PrivateTradingAccountFullTradingAccountDetails';
import { PrivateTradingAccountOwnerActions } from './PrivateTradingAccountOwnerActions';

import ApiClient from "../ApiClient";

export class PrivateTradingAccountFull { 
    public 'id': string;
    public 'publicInfo': PrivateTradingAccountFullPublicDetails;
    public 'tradingAccountInfo': PrivateTradingAccountFullTradingAccountDetails;
    public 'brokerDetails': BrokerDetails;
    public 'ownerActions': PrivateTradingAccountOwnerActions;

    constructor(data: {[key: string]: any}) { 
        this['id'] = data['id'];
        this['publicInfo'] = data['publicInfo'];
        this['tradingAccountInfo'] = data['tradingAccountInfo'];
        this['brokerDetails'] = data['brokerDetails'];
        this['ownerActions'] = data['ownerActions'];
    }

    static constructFromObject(data: {[key: string]: any}): PrivateTradingAccountFull | undefined {
        if (data) {
            return new PrivateTradingAccountFull({ 
                'id': ApiClient.convertToType(data['id'], 'string'),
                'publicInfo': PrivateTradingAccountFullPublicDetails.constructFromObject(data['publicInfo']),
                'tradingAccountInfo': PrivateTradingAccountFullTradingAccountDetails.constructFromObject(data['tradingAccountInfo']),
                'brokerDetails': BrokerDetails.constructFromObject(data['brokerDetails']),
                'ownerActions': PrivateTradingAccountOwnerActions.constructFromObject(data['ownerActions']),
            });
        }
    }
}



