/**
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";

export class PrivateTradingAccountOwnerActions { 
    public 'canClose': boolean;
    public 'canChangePassword': boolean;
    public 'canTransferMoney': boolean;
    public 'canMakeDemoDeposit': boolean;
    public 'canMakeProgramFromPrivateTradingAccount': boolean;
    public 'canMakeSignalProviderFromPrivateTradingAccount': boolean;
    public 'canMakeSignalProviderFromPrivateExternalTradingAccount': boolean;
    public 'canMakeProgramFromSignalProvider': boolean;
    public 'canMakeSignalProviderFromProgram': boolean;
    public 'canEditSignalProviderSettings': boolean;
    public 'isEnoughMoneyToCreateProgram': boolean;
    public 'canConfirm2FA': boolean;

    constructor(data: {[key: string]: any}) { 
        this['canClose'] = data['canClose'];
        this['canChangePassword'] = data['canChangePassword'];
        this['canTransferMoney'] = data['canTransferMoney'];
        this['canMakeDemoDeposit'] = data['canMakeDemoDeposit'];
        this['canMakeProgramFromPrivateTradingAccount'] = data['canMakeProgramFromPrivateTradingAccount'];
        this['canMakeSignalProviderFromPrivateTradingAccount'] = data['canMakeSignalProviderFromPrivateTradingAccount'];
        this['canMakeSignalProviderFromPrivateExternalTradingAccount'] = data['canMakeSignalProviderFromPrivateExternalTradingAccount'];
        this['canMakeProgramFromSignalProvider'] = data['canMakeProgramFromSignalProvider'];
        this['canMakeSignalProviderFromProgram'] = data['canMakeSignalProviderFromProgram'];
        this['canEditSignalProviderSettings'] = data['canEditSignalProviderSettings'];
        this['isEnoughMoneyToCreateProgram'] = data['isEnoughMoneyToCreateProgram'];
        this['canConfirm2FA'] = data['canConfirm2FA'];
    }

    static constructFromObject(data: {[key: string]: any}): PrivateTradingAccountOwnerActions | undefined {
        if (data) {
            return new PrivateTradingAccountOwnerActions({ 
                'canClose': ApiClient.convertToType(data['canClose'], 'boolean'),
                'canChangePassword': ApiClient.convertToType(data['canChangePassword'], 'boolean'),
                'canTransferMoney': ApiClient.convertToType(data['canTransferMoney'], 'boolean'),
                'canMakeDemoDeposit': ApiClient.convertToType(data['canMakeDemoDeposit'], 'boolean'),
                'canMakeProgramFromPrivateTradingAccount': ApiClient.convertToType(data['canMakeProgramFromPrivateTradingAccount'], 'boolean'),
                'canMakeSignalProviderFromPrivateTradingAccount': ApiClient.convertToType(data['canMakeSignalProviderFromPrivateTradingAccount'], 'boolean'),
                'canMakeSignalProviderFromPrivateExternalTradingAccount': ApiClient.convertToType(data['canMakeSignalProviderFromPrivateExternalTradingAccount'], 'boolean'),
                'canMakeProgramFromSignalProvider': ApiClient.convertToType(data['canMakeProgramFromSignalProvider'], 'boolean'),
                'canMakeSignalProviderFromProgram': ApiClient.convertToType(data['canMakeSignalProviderFromProgram'], 'boolean'),
                'canEditSignalProviderSettings': ApiClient.convertToType(data['canEditSignalProviderSettings'], 'boolean'),
                'isEnoughMoneyToCreateProgram': ApiClient.convertToType(data['isEnoughMoneyToCreateProgram'], 'boolean'),
                'canConfirm2FA': ApiClient.convertToType(data['canConfirm2FA'], 'boolean'),
            });
        }
    }
}



