/**
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";

export class ProgramWithdrawInfo { 
    public 'periodEnds': Date;
    public 'title': string;
    public 'availableToWithdraw': number;
    public 'isOwner': boolean;
    public 'withheldInvestment': number;

    constructor(data: {[key: string]: any}) { 
        this['periodEnds'] = data['periodEnds'];
        this['title'] = data['title'];
        this['availableToWithdraw'] = data['availableToWithdraw'];
        this['isOwner'] = data['isOwner'];
        this['withheldInvestment'] = data['withheldInvestment'];
    }

    static constructFromObject(data: {[key: string]: any}): ProgramWithdrawInfo | undefined {
        if (data) {
            return new ProgramWithdrawInfo({ 
                'periodEnds': ApiClient.convertToType(data['periodEnds'], 'Date'),
                'title': ApiClient.convertToType(data['title'], 'string'),
                'availableToWithdraw': ApiClient.convertToType(data['availableToWithdraw'], 'number'),
                'isOwner': ApiClient.convertToType(data['isOwner'], 'boolean'),
                'withheldInvestment': ApiClient.convertToType(data['withheldInvestment'], 'number'),
            });
        }
    }
}



