/**
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";

export class SignalTradingEvent { 
    public 'date': Date;
    public 'message': string;

    constructor(data: {[key: string]: any}) { 
        this['date'] = data['date'];
        this['message'] = data['message'];
    }

    static constructFromObject(data: {[key: string]: any}): SignalTradingEvent | undefined {
        if (data) {
            return new SignalTradingEvent({ 
                'date': ApiClient.convertToType(data['date'], 'Date'),
                'message': ApiClient.convertToType(data['message'], 'string'),
            });
        }
    }
}



