/**
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import ApiClient from "../ApiClient";

export class TwoFactorAuthenticator { 
    public 'sharedKey': string;
    public 'authenticatorUri': string;

    constructor(data: {[key: string]: any}) { 
        this['sharedKey'] = data['sharedKey'];
        this['authenticatorUri'] = data['authenticatorUri'];
    }

    static constructFromObject(data: {[key: string]: any}): TwoFactorAuthenticator | undefined {
        if (data) {
            return new TwoFactorAuthenticator({ 
                'sharedKey': ApiClient.convertToType(data['sharedKey'], 'string'),
                'authenticatorUri': ApiClient.convertToType(data['authenticatorUri'], 'string'),
            });
        }
    }
}



