/**
 * Core API v2.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './Currency';

import ApiClient from "../ApiClient";

export class WalletBaseData { 
    public 'id': string;
    public 'title': string;
    public 'logo': string;
    public 'currency': Currency;
    public 'available': number;
    public 'rate': number;

    constructor(data: {[key: string]: any}) { 
        this['id'] = data['id'];
        this['title'] = data['title'];
        this['logo'] = data['logo'];
        this['currency'] = data['currency'];
        this['available'] = data['available'];
        this['rate'] = data['rate'];
    }

    static constructFromObject(data: {[key: string]: any}): WalletBaseData | undefined {
        if (data) {
            return new WalletBaseData({ 
                'id': ApiClient.convertToType(data['id'], 'string'),
                'title': ApiClient.convertToType(data['title'], 'string'),
                'logo': ApiClient.convertToType(data['logo'], 'string'),
                'currency': Currency.constructFromObject(data['currency']),
                'available': ApiClient.convertToType(data['available'], 'number'),
                'rate': ApiClient.convertToType(data['rate'], 'number'),
            });
        }
    }
}



