'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Core API v1.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: v1.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _BrokerInvestmentProgram = require('./BrokerInvestmentProgram');

var _BrokerInvestmentProgram2 = _interopRequireDefault(_BrokerInvestmentProgram);

var _ManagerRequest = require('./ManagerRequest');

var _ManagerRequest2 = _interopRequireDefault(_ManagerRequest);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The BrokerInitData model module.
* @module model/BrokerInitData
* @version v1.0
*/
var BrokerInitData = function () {
    /**
    * Constructs a new <code>BrokerInitData</code>.
    * @alias module:model/BrokerInitData
    * @class
    */

    function BrokerInitData() {
        _classCallCheck(this, BrokerInitData);

        this.newManagerRequest = undefined;
        this.investments = undefined;
        this.hoursOffset = undefined;
    }

    /**
    * Constructs a <code>BrokerInitData</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BrokerInitData} obj Optional instance to populate.
    * @return {module:model/BrokerInitData} The populated <code>BrokerInitData</code> instance.
    */


    _createClass(BrokerInitData, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new BrokerInitData();

                if (data.hasOwnProperty('newManagerRequest')) {
                    obj['newManagerRequest'] = _ApiClient2.default.convertToType(data['newManagerRequest'], [_ManagerRequest2.default]);
                }
                if (data.hasOwnProperty('investments')) {
                    obj['investments'] = _ApiClient2.default.convertToType(data['investments'], [_BrokerInvestmentProgram2.default]);
                }
                if (data.hasOwnProperty('hoursOffset')) {
                    obj['hoursOffset'] = _ApiClient2.default.convertToType(data['hoursOffset'], 'Number');
                }
            }
            return obj;
        }

        /**
        * @member {Array.<module:model/ManagerRequest>} newManagerRequest
        */

        /**
        * @member {Array.<module:model/BrokerInvestmentProgram>} investments
        */

        /**
        * @member {Number} hoursOffset
        */

    }]);

    return BrokerInitData;
}();

exports.default = BrokerInitData;