'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Core API v1.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: v1.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _ProfilePublic = require('./ProfilePublic');

var _ProfilePublic2 = _interopRequireDefault(_ProfilePublic);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 *
 * @interface OpenSignalTrade
 */

/**
 *
 * @name OpenSignalTrade#id
 * @type {String}
 */
/**
 *
 * @name OpenSignalTrade#symbol
 * @type {String}
 */
/**
 *
 * @name OpenSignalTrade#manager
 * @type {ProfilePublic}
 */
/**
 *
 * @name OpenSignalTrade#orderId
 * @type {Number}
 */
/**
 *
 * @name OpenSignalTrade#openDate
 * @type {Date}
 */
/**
 *
 * @name OpenSignalTrade#openPrice
 * @type {Number}
 */
/**
 *
 * @name OpenSignalTrade#volume
 * @type {Number}
 */
/**
 *
 * @name OpenSignalTrade#price
 * @type {Number}
 */
/**
 *
 * @name OpenSignalTrade#profit
 * @type {Number}
 */

var OpenSignalTrade = function () {
    function OpenSignalTrade() {
        _classCallCheck(this, OpenSignalTrade);

        this.id = undefined;
        this.symbol = undefined;
        this.manager = undefined;
        this.orderId = undefined;
        this.openDate = undefined;
        this.openPrice = undefined;
        this.volume = undefined;
        this.price = undefined;
        this.profit = undefined;
    }

    _createClass(OpenSignalTrade, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new OpenSignalTrade();

                if (data.hasOwnProperty('id')) {
                    obj['id'] = _ApiClient2.default.convertToType(data['id'], 'String');
                }
                if (data.hasOwnProperty('symbol')) {
                    obj['symbol'] = _ApiClient2.default.convertToType(data['symbol'], 'String');
                }
                if (data.hasOwnProperty('manager')) {
                    obj['manager'] = _ProfilePublic2.default.constructFromObject(data['manager']);
                }
                if (data.hasOwnProperty('orderId')) {
                    obj['orderId'] = _ApiClient2.default.convertToType(data['orderId'], 'Number');
                }
                if (data.hasOwnProperty('openDate')) {
                    obj['openDate'] = _ApiClient2.default.convertToType(data['openDate'], 'Date');
                }
                if (data.hasOwnProperty('openPrice')) {
                    obj['openPrice'] = _ApiClient2.default.convertToType(data['openPrice'], 'Number');
                }
                if (data.hasOwnProperty('volume')) {
                    obj['volume'] = _ApiClient2.default.convertToType(data['volume'], 'Number');
                }
                if (data.hasOwnProperty('price')) {
                    obj['price'] = _ApiClient2.default.convertToType(data['price'], 'Number');
                }
                if (data.hasOwnProperty('profit')) {
                    obj['profit'] = _ApiClient2.default.convertToType(data['profit'], 'Number');
                }
            }
            return obj;
        }
    }]);

    return OpenSignalTrade;
}();

exports.default = OpenSignalTrade;