'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Core API v1.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: v1.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _AmountWithCurrency = require('./AmountWithCurrency');

var _AmountWithCurrency2 = _interopRequireDefault(_AmountWithCurrency);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 *
 * @interface ProgramDetailsListStatistic
 */

/**
 *
 * @name ProgramDetailsListStatistic#balanceBase
 * @type {AmountWithCurrency}
 */
/**
 *
 * @name ProgramDetailsListStatistic#balanceGVT
 * @type {AmountWithCurrency}
 */
/**
 *
 * @name ProgramDetailsListStatistic#balanceSecondary
 * @type {AmountWithCurrency}
 */
/**
 *
 * @name ProgramDetailsListStatistic#currentValue
 * @type {Number}
 */
/**
 *
 * @name ProgramDetailsListStatistic#profitPercent
 * @type {Number}
 */
/**
 *
 * @name ProgramDetailsListStatistic#profitValue
 * @type {Number}
 */
/**
 *
 * @name ProgramDetailsListStatistic#drawdownPercent
 * @type {Number}
 */
/**
 *
 * @name ProgramDetailsListStatistic#investorsCount
 * @type {Number}
 */
/**
 *
 * @name ProgramDetailsListStatistic#tradesCount
 * @type {Number}
 */

var ProgramDetailsListStatistic = function () {
    function ProgramDetailsListStatistic() {
        _classCallCheck(this, ProgramDetailsListStatistic);

        this.balanceBase = undefined;
        this.balanceGVT = undefined;
        this.balanceSecondary = undefined;
        this.currentValue = undefined;
        this.profitPercent = undefined;
        this.profitValue = undefined;
        this.drawdownPercent = undefined;
        this.investorsCount = undefined;
        this.tradesCount = undefined;
    }

    _createClass(ProgramDetailsListStatistic, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new ProgramDetailsListStatistic();

                if (data.hasOwnProperty('balanceBase')) {
                    obj['balanceBase'] = _AmountWithCurrency2.default.constructFromObject(data['balanceBase']);
                }
                if (data.hasOwnProperty('balanceGVT')) {
                    obj['balanceGVT'] = _AmountWithCurrency2.default.constructFromObject(data['balanceGVT']);
                }
                if (data.hasOwnProperty('balanceSecondary')) {
                    obj['balanceSecondary'] = _AmountWithCurrency2.default.constructFromObject(data['balanceSecondary']);
                }
                if (data.hasOwnProperty('currentValue')) {
                    obj['currentValue'] = _ApiClient2.default.convertToType(data['currentValue'], 'Number');
                }
                if (data.hasOwnProperty('profitPercent')) {
                    obj['profitPercent'] = _ApiClient2.default.convertToType(data['profitPercent'], 'Number');
                }
                if (data.hasOwnProperty('profitValue')) {
                    obj['profitValue'] = _ApiClient2.default.convertToType(data['profitValue'], 'Number');
                }
                if (data.hasOwnProperty('drawdownPercent')) {
                    obj['drawdownPercent'] = _ApiClient2.default.convertToType(data['drawdownPercent'], 'Number');
                }
                if (data.hasOwnProperty('investorsCount')) {
                    obj['investorsCount'] = _ApiClient2.default.convertToType(data['investorsCount'], 'Number');
                }
                if (data.hasOwnProperty('tradesCount')) {
                    obj['tradesCount'] = _ApiClient2.default.convertToType(data['tradesCount'], 'Number');
                }
            }
            return obj;
        }
    }]);

    return ProgramDetailsListStatistic;
}();

exports.default = ProgramDetailsListStatistic;