/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
 *
 * @interface AssetType
 */



/**
* Enum class AssetType.
* @enum {}
* @readonly
*/
export default class AssetType {
    
        /**
         * value: "None"
         * @const
         */
        None = "None";

    
        /**
         * value: "Programs"
         * @const
         */
        Programs = "Programs";

    
        /**
         * value: "Funds"
         * @const
         */
        Funds = "Funds";

    
        /**
         * value: "Signals"
         * @const
         */
        Signals = "Signals";

    
        /**
         * value: "TradingAccounts"
         * @const
         */
        TradingAccounts = "TradingAccounts";

    
        /**
         * value: "External"
         * @const
         */
        External = "External";

    

    /**
    * Returns a <code>AssetType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AssetType} The enum <code>AssetType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}


