/**
 * Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The DateChart model module.
* @module model/DateChart
* @version v1
*/
export default class DateChart {
    /**
    * Constructs a new <code>DateChart</code>.
    * @alias module:model/DateChart
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>DateChart</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DateChart} obj Optional instance to populate.
    * @return {module:model/DateChart} The populated <code>DateChart</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DateChart();

            
            
            

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {Number} amount
    */
    amount = undefined;
    /**
    * @member {Date} date
    */
    date = undefined;








}


