/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ErrorMessage from './ErrorMessage';





/**
* The ErrorViewModel model module.
* @module model/ErrorViewModel
* @version v1.0
*/
export default class ErrorViewModel {
    /**
    * Constructs a new <code>ErrorViewModel</code>.
    * @alias module:model/ErrorViewModel
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ErrorViewModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ErrorViewModel} obj Optional instance to populate.
    * @return {module:model/ErrorViewModel} The populated <code>ErrorViewModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorViewModel();

            
            
            

            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [ErrorMessage]);
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/ErrorMessage>} errors
    */
    errors = undefined;
    /**
    * @member {module:model/ErrorViewModel.CodeEnum} code
    */
    code = undefined;






    /**
    * Allowed values for the <code>code</code> property.
    * @enum {String}
    * @readonly
    */
    static CodeEnum = {
    
        /**
         * value: "InternalServerError"
         * @const
         */
        "InternalServerError": "InternalServerError",
    
        /**
         * value: "ValidationError"
         * @const
         */
        "ValidationError": "ValidationError",
    
        /**
         * value: "RequiresTwoFactor"
         * @const
         */
        "RequiresTwoFactor": "RequiresTwoFactor"    
    };



}


