/**
 * Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ManagerProfitChartData from './ManagerProfitChartData';





/**
* The ManagerProfitChart model module.
* @module model/ManagerProfitChart
* @version v1
*/
export default class ManagerProfitChart {
    /**
    * Constructs a new <code>ManagerProfitChart</code>.
    * @alias module:model/ManagerProfitChart
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ManagerProfitChart</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ManagerProfitChart} obj Optional instance to populate.
    * @return {module:model/ManagerProfitChart} The populated <code>ManagerProfitChart</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ManagerProfitChart();

            
            
            

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [ManagerProfitChartData]);
            }
        }
        return obj;
    }

    /**
    * @member {String} title
    */
    title = undefined;
    /**
    * @member {Array.<module:model/ManagerProfitChartData>} data
    */
    data = undefined;








}


