/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MultiWalletTransaction'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MultiWalletTransaction'));
  } else {
    // Browser globals (root is window)
    if (!root.CoreApiV10) {
      root.CoreApiV10 = {};
    }
    root.CoreApiV10.MultiWalletTransactionsViewModel = factory(root.CoreApiV10.ApiClient, root.CoreApiV10.MultiWalletTransaction);
  }
}(this, function(ApiClient, MultiWalletTransaction) {
  'use strict';




  /**
   * The MultiWalletTransactionsViewModel model module.
   * @module model/MultiWalletTransactionsViewModel
   * @version v1.0
   */

  /**
   * Constructs a new <code>MultiWalletTransactionsViewModel</code>.
   * @alias module:model/MultiWalletTransactionsViewModel
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>MultiWalletTransactionsViewModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MultiWalletTransactionsViewModel} obj Optional instance to populate.
   * @return {module:model/MultiWalletTransactionsViewModel} The populated <code>MultiWalletTransactionsViewModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('transactions')) {
        obj['transactions'] = ApiClient.convertToType(data['transactions'], [MultiWalletTransaction]);
      }
      if (data.hasOwnProperty('total')) {
        obj['total'] = ApiClient.convertToType(data['total'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/MultiWalletTransaction>} transactions
   */
  exports.prototype['transactions'] = undefined;
  /**
   * @member {Number} total
   */
  exports.prototype['total'] = undefined;



  return exports;
}));


