/**
 * Core API v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The NewManager model module.
* @module model/NewManager
* @version v2.0
*/
export default class NewManager {
    /**
    * Constructs a new <code>NewManager</code>.
    * @alias module:model/NewManager
    * @class
    * @param requestId {String} 
    * @param login {String} 
    */

    constructor(requestId, login) {
        

        
        

        this['requestId'] = requestId;this['login'] = login;

        
    }

    /**
    * Constructs a <code>NewManager</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NewManager} obj Optional instance to populate.
    * @return {module:model/NewManager} The populated <code>NewManager</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewManager();

            
            
            

            if (data.hasOwnProperty('requestId')) {
                obj['requestId'] = ApiClient.convertToType(data['requestId'], 'String');
            }
            if (data.hasOwnProperty('login')) {
                obj['login'] = ApiClient.convertToType(data['login'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} requestId
    */
    requestId = undefined;
    /**
    * @member {String} login
    */
    login = undefined;








}


