/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
 *
 * @interface OrderProgramData
 */

/**
 *
 * @name OrderProgramData#title
 * @type {String}
 */
/**
 *
 * @name OrderProgramData#level
 * @type {Number}
 */
/**
 *
 * @name OrderProgramData#levelProgress
 * @type {Number}
 */
/**
 *
 * @name OrderProgramData#color
 * @type {String}
 */
/**
 *
 * @name OrderProgramData#url
 * @type {String}
 */
/**
 *
 * @name OrderProgramData#logo
 * @type {String}
 */





export default class OrderProgramData {

    constructor() {
        

        
        

        

        
    }

    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderProgramData();

            
            
            

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'Number');
            }
            if (data.hasOwnProperty('levelProgress')) {
                obj['levelProgress'] = ApiClient.convertToType(data['levelProgress'], 'Number');
            }
            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
            }
        }
        return obj;
    }

    title = undefined;
    level = undefined;
    levelProgress = undefined;
    color = undefined;
    url = undefined;
    logo = undefined;








}






