/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
 *
 * @interface PlatformStatisticOld
 */

/**
 *
 * @name PlatformStatisticOld#managers
 * @type {Number}
 */
/**
 *
 * @name PlatformStatisticOld#investors
 * @type {Number}
 */
/**
 *
 * @name PlatformStatisticOld#profitWeek
 * @type {Number}
 */
/**
 *
 * @name PlatformStatisticOld#investmentAmount
 * @type {Number}
 */
/**
 *
 * @name PlatformStatisticOld#totalInvestorsProfit
 * @type {Number}
 */
/**
 *
 * @name PlatformStatisticOld#totalProfit
 * @type {Number}
 */





export default class PlatformStatisticOld {

    constructor() {
        

        
        

        

        
    }

    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlatformStatisticOld();

            
            
            

            if (data.hasOwnProperty('managers')) {
                obj['managers'] = ApiClient.convertToType(data['managers'], 'Number');
            }
            if (data.hasOwnProperty('investors')) {
                obj['investors'] = ApiClient.convertToType(data['investors'], 'Number');
            }
            if (data.hasOwnProperty('profitWeek')) {
                obj['profitWeek'] = ApiClient.convertToType(data['profitWeek'], 'Number');
            }
            if (data.hasOwnProperty('investmentAmount')) {
                obj['investmentAmount'] = ApiClient.convertToType(data['investmentAmount'], 'Number');
            }
            if (data.hasOwnProperty('totalInvestorsProfit')) {
                obj['totalInvestorsProfit'] = ApiClient.convertToType(data['totalInvestorsProfit'], 'Number');
            }
            if (data.hasOwnProperty('totalProfit')) {
                obj['totalProfit'] = ApiClient.convertToType(data['totalProfit'], 'Number');
            }
        }
        return obj;
    }

    managers = undefined;
    investors = undefined;
    profitWeek = undefined;
    investmentAmount = undefined;
    totalInvestorsProfit = undefined;
    totalProfit = undefined;








}






