/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AndroidAppVersion', 'model/Enums', 'model/FundFacet', 'model/IOsAppVersion', 'model/PlatformCurrency', 'model/ProgramFacet', 'model/ProgramsInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AndroidAppVersion'), require('./Enums'), require('./FundFacet'), require('./IOsAppVersion'), require('./PlatformCurrency'), require('./ProgramFacet'), require('./ProgramsInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.CoreApiV10) {
      root.CoreApiV10 = {};
    }
    root.CoreApiV10.PlatformInfo = factory(root.CoreApiV10.ApiClient, root.CoreApiV10.AndroidAppVersion, root.CoreApiV10.Enums, root.CoreApiV10.FundFacet, root.CoreApiV10.IOsAppVersion, root.CoreApiV10.PlatformCurrency, root.CoreApiV10.ProgramFacet, root.CoreApiV10.ProgramsInfo);
  }
}(this, function(ApiClient, AndroidAppVersion, Enums, FundFacet, IOsAppVersion, PlatformCurrency, ProgramFacet, ProgramsInfo) {
  'use strict';




  /**
   * The PlatformInfo model module.
   * @module model/PlatformInfo
   * @version v1.0
   */

  /**
   * Constructs a new <code>PlatformInfo</code>.
   * @alias module:model/PlatformInfo
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>PlatformInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PlatformInfo} obj Optional instance to populate.
   * @return {module:model/PlatformInfo} The populated <code>PlatformInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('iOSVersion')) {
        obj['iOSVersion'] = IOsAppVersion.constructFromObject(data['iOSVersion']);
      }
      if (data.hasOwnProperty('androidVersion')) {
        obj['androidVersion'] = AndroidAppVersion.constructFromObject(data['androidVersion']);
      }
      if (data.hasOwnProperty('programsFacets')) {
        obj['programsFacets'] = ApiClient.convertToType(data['programsFacets'], [ProgramFacet]);
      }
      if (data.hasOwnProperty('fundsFacets')) {
        obj['fundsFacets'] = ApiClient.convertToType(data['fundsFacets'], [FundFacet]);
      }
      if (data.hasOwnProperty('programsInfo')) {
        obj['programsInfo'] = ProgramsInfo.constructFromObject(data['programsInfo']);
      }
      if (data.hasOwnProperty('currencies')) {
        obj['currencies'] = ApiClient.convertToType(data['currencies'], ['String']);
      }
      if (data.hasOwnProperty('platformCurrencies')) {
        obj['platformCurrencies'] = ApiClient.convertToType(data['platformCurrencies'], [PlatformCurrency]);
      }
      if (data.hasOwnProperty('enums')) {
        obj['enums'] = Enums.constructFromObject(data['enums']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/IOsAppVersion} iOSVersion
   */
  exports.prototype['iOSVersion'] = undefined;
  /**
   * @member {module:model/AndroidAppVersion} androidVersion
   */
  exports.prototype['androidVersion'] = undefined;
  /**
   * @member {Array.<module:model/ProgramFacet>} programsFacets
   */
  exports.prototype['programsFacets'] = undefined;
  /**
   * @member {Array.<module:model/FundFacet>} fundsFacets
   */
  exports.prototype['fundsFacets'] = undefined;
  /**
   * @member {module:model/ProgramsInfo} programsInfo
   */
  exports.prototype['programsInfo'] = undefined;
  /**
   * @member {Array.<String>} currencies
   */
  exports.prototype['currencies'] = undefined;
  /**
   * @member {Array.<module:model/PlatformCurrency>} platformCurrencies
   */
  exports.prototype['platformCurrencies'] = undefined;
  /**
   * @member {module:model/Enums} enums
   */
  exports.prototype['enums'] = undefined;



  return exports;
}));


