/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import NotificationSettingViewModel from './NotificationSettingViewModel';





    /**
     *
     * @interface ProgramNotificationSettingList
     */
    
    /**
     *
     * @name ProgramNotificationSettingList#level
     * @type {Number}
     */
    /**
     *
     * @name ProgramNotificationSettingList#settingsCustom
     * @type {Array<NotificationSettingViewModel>}
     */
    /**
     *
     * @name ProgramNotificationSettingList#assetId
     * @type {String}
     */
    /**
     *
     * @name ProgramNotificationSettingList#title
     * @type {String}
     */
    /**
     *
     * @name ProgramNotificationSettingList#url
     * @type {String}
     */
    /**
     *
     * @name ProgramNotificationSettingList#logo
     * @type {String}
     */
    /**
     *
     * @name ProgramNotificationSettingList#settingsGeneral
     * @type {Array<NotificationSettingViewModel>}
     */





export default class ProgramNotificationSettingList {

    constructor() {
        

        
        

        

        
    }

    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProgramNotificationSettingList();

            
            
            

            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'Number');
            }
            if (data.hasOwnProperty('settingsCustom')) {
                obj['settingsCustom'] = ApiClient.convertToType(data['settingsCustom'], [NotificationSettingViewModel]);
            }
            if (data.hasOwnProperty('assetId')) {
                obj['assetId'] = ApiClient.convertToType(data['assetId'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
            }
            if (data.hasOwnProperty('settingsGeneral')) {
                obj['settingsGeneral'] = ApiClient.convertToType(data['settingsGeneral'], [NotificationSettingViewModel]);
            }
        }
        return obj;
    }

    level = undefined;
    settingsCustom = undefined;
    assetId = undefined;
    title = undefined;
    url = undefined;
    logo = undefined;
    settingsGeneral = undefined;








}


