/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ProgramRequest from './ProgramRequest';





/**
* The ProgramRequests model module.
* @module model/ProgramRequests
* @version v1.0
*/
export default class ProgramRequests {
    /**
    * Constructs a new <code>ProgramRequests</code>.
    * @alias module:model/ProgramRequests
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ProgramRequests</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ProgramRequests} obj Optional instance to populate.
    * @return {module:model/ProgramRequests} The populated <code>ProgramRequests</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProgramRequests();

            
            
            

            if (data.hasOwnProperty('requests')) {
                obj['requests'] = ApiClient.convertToType(data['requests'], [ProgramRequest]);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('totalValue')) {
                obj['totalValue'] = ApiClient.convertToType(data['totalValue'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/ProgramRequest>} requests
    */
    requests = undefined;
    /**
    * @member {Number} total
    */
    total = undefined;
    /**
    * @member {Number} totalValue
    */
    totalValue = undefined;








}


