/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import RateItem from './RateItem';





    /**
     *
     * @interface RatesModelRates
     */
    
    /**
     *
     * @name RatesModelRates#Undefined
     * @type {[RateItem]}
     */
    /**
     *
     * @name RatesModelRates#GVT
     * @type {[RateItem]}
     */
    /**
     *
     * @name RatesModelRates#ETH
     * @type {[RateItem]}
     */
    /**
     *
     * @name RatesModelRates#BTC
     * @type {[RateItem]}
     */
    /**
     *
     * @name RatesModelRates#ADA
     * @type {[RateItem]}
     */
    /**
     *
     * @name RatesModelRates#USDT
     * @type {[RateItem]}
     */
    /**
     *
     * @name RatesModelRates#XRP
     * @type {[RateItem]}
     */
    /**
     *
     * @name RatesModelRates#BCH
     * @type {[RateItem]}
     */
    /**
     *
     * @name RatesModelRates#LTC
     * @type {[RateItem]}
     */
    /**
     *
     * @name RatesModelRates#DOGE
     * @type {[RateItem]}
     */
    /**
     *
     * @name RatesModelRates#BNB
     * @type {[RateItem]}
     */
    /**
     *
     * @name RatesModelRates#USD
     * @type {[RateItem]}
     */
    /**
     *
     * @name RatesModelRates#EUR
     * @type {[RateItem]}
     */





export default class RatesModelRates {

    constructor() {
        

        
        

        

        
    }

    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RatesModelRates();

            
            
            

            if (data.hasOwnProperty('Undefined')) {
                obj['Undefined'] = ApiClient.convertToType(data['Undefined'], [RateItem]);
            }
            if (data.hasOwnProperty('GVT')) {
                obj['GVT'] = ApiClient.convertToType(data['GVT'], [RateItem]);
            }
            if (data.hasOwnProperty('ETH')) {
                obj['ETH'] = ApiClient.convertToType(data['ETH'], [RateItem]);
            }
            if (data.hasOwnProperty('BTC')) {
                obj['BTC'] = ApiClient.convertToType(data['BTC'], [RateItem]);
            }
            if (data.hasOwnProperty('ADA')) {
                obj['ADA'] = ApiClient.convertToType(data['ADA'], [RateItem]);
            }
            if (data.hasOwnProperty('USDT')) {
                obj['USDT'] = ApiClient.convertToType(data['USDT'], [RateItem]);
            }
            if (data.hasOwnProperty('XRP')) {
                obj['XRP'] = ApiClient.convertToType(data['XRP'], [RateItem]);
            }
            if (data.hasOwnProperty('BCH')) {
                obj['BCH'] = ApiClient.convertToType(data['BCH'], [RateItem]);
            }
            if (data.hasOwnProperty('LTC')) {
                obj['LTC'] = ApiClient.convertToType(data['LTC'], [RateItem]);
            }
            if (data.hasOwnProperty('DOGE')) {
                obj['DOGE'] = ApiClient.convertToType(data['DOGE'], [RateItem]);
            }
            if (data.hasOwnProperty('BNB')) {
                obj['BNB'] = ApiClient.convertToType(data['BNB'], [RateItem]);
            }
            if (data.hasOwnProperty('USD')) {
                obj['USD'] = ApiClient.convertToType(data['USD'], [RateItem]);
            }
            if (data.hasOwnProperty('EUR')) {
                obj['EUR'] = ApiClient.convertToType(data['EUR'], [RateItem]);
            }
        }
        return obj;
    }

    Undefined = undefined;
    GVT = undefined;
    ETH = undefined;
    BTC = undefined;
    ADA = undefined;
    USDT = undefined;
    XRP = undefined;
    BCH = undefined;
    LTC = undefined;
    DOGE = undefined;
    BNB = undefined;
    USD = undefined;
    EUR = undefined;








}


