/**
 * Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import RecoveryCode from './RecoveryCode';





/**
* The RecoveryCodesViewModel model module.
* @module model/RecoveryCodesViewModel
* @version v1
*/
export default class RecoveryCodesViewModel {
    /**
    * Constructs a new <code>RecoveryCodesViewModel</code>.
    * @alias module:model/RecoveryCodesViewModel
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>RecoveryCodesViewModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RecoveryCodesViewModel} obj Optional instance to populate.
    * @return {module:model/RecoveryCodesViewModel} The populated <code>RecoveryCodesViewModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecoveryCodesViewModel();

            
            
            

            if (data.hasOwnProperty('codes')) {
                obj['codes'] = ApiClient.convertToType(data['codes'], [RecoveryCode]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/RecoveryCode>} codes
    */
    codes = undefined;








}


