/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import CaptchaCheckResult from './CaptchaCheckResult';





/**
 *
 * @interface RegisterViewModel
 */

/**
 *
 * @name RegisterViewModel#password
 * @type {String}
 */
/**
 *
 * @name RegisterViewModel#confirmPassword
 * @type {String}
 */
/**
 *
 * @name RegisterViewModel#userName
 * @type {String}
 */
/**
 *
 * @name RegisterViewModel#refCode
 * @type {String}
 */
/**
 *
 * @name RegisterViewModel#isAuto
 * @type {Boolean}
 */
/**
 *
 * @name RegisterViewModel#email
 * @type {String}
 */
/**
 *
 * @name RegisterViewModel#captchaCheckResult
 * @type {CaptchaCheckResult}
 */





export default class RegisterViewModel {

    constructor(password, email) {
        

        
        

        this['password'] = password;this['email'] = email;

        
    }

    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegisterViewModel();

            
            
            

            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('confirmPassword')) {
                obj['confirmPassword'] = ApiClient.convertToType(data['confirmPassword'], 'String');
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('refCode')) {
                obj['refCode'] = ApiClient.convertToType(data['refCode'], 'String');
            }
            if (data.hasOwnProperty('isAuto')) {
                obj['isAuto'] = ApiClient.convertToType(data['isAuto'], 'Boolean');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('captchaCheckResult')) {
                obj['captchaCheckResult'] = CaptchaCheckResult.constructFromObject(data['captchaCheckResult']);
            }
        }
        return obj;
    }

    password = undefined;
    confirmPassword = undefined;
    userName = undefined;
    refCode = undefined;
    isAuto = undefined;
    email = undefined;
    captchaCheckResult = undefined;








}






