/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





    /**
     *
     * @interface Review
     */
    
    /**
     *
     * @name Review#moderationComment
     * @type {String}
     */
    /**
     *
     * @name Review#clientComment
     * @type {String}
     */
    /**
     *
     * @name Review#reviewAnswer
     * @type {String}
     */
    /**
     *
     * @name Review#rejectLabels
     * @type {Array<String>}
     */
    /**
     *
     * @name Review#reviewRejectType
     * @type {String}
     */





export default class Review {

    constructor() {
        

        
        

        

        
    }

    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Review();

            
            
            

            if (data.hasOwnProperty('moderationComment')) {
                obj['moderationComment'] = ApiClient.convertToType(data['moderationComment'], 'String');
            }
            if (data.hasOwnProperty('clientComment')) {
                obj['clientComment'] = ApiClient.convertToType(data['clientComment'], 'String');
            }
            if (data.hasOwnProperty('reviewAnswer')) {
                obj['reviewAnswer'] = ApiClient.convertToType(data['reviewAnswer'], 'String');
            }
            if (data.hasOwnProperty('rejectLabels')) {
                obj['rejectLabels'] = ApiClient.convertToType(data['rejectLabels'], ['String']);
            }
            if (data.hasOwnProperty('reviewRejectType')) {
                obj['reviewRejectType'] = ApiClient.convertToType(data['reviewRejectType'], 'String');
            }
        }
        return obj;
    }

    moderationComment = undefined;
    clientComment = undefined;
    reviewAnswer = undefined;
    rejectLabels = undefined;
    reviewRejectType = undefined;








}


