/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
 *
 * @interface SocialLinkViewModel
 */

/**
 *
 * @name SocialLinkViewModel#id
 * @type {String}
 */
/**
 *
 * @name SocialLinkViewModel#url
 * @type {String}
 */
/**
 *
 * @name SocialLinkViewModel#logo
 * @type {String}
 */
/**
 *
 * @name SocialLinkViewModel#name
 * @type {String}
 */
/**
 *
 * @name SocialLinkViewModel#value
 * @type {String}
 */





export default class SocialLinkViewModel {

    constructor() {
        

        
        

        

        
    }

    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SocialLinkViewModel();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    id = undefined;
    url = undefined;
    logo = undefined;
    name = undefined;
    value = undefined;








}






