/**
 * Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The WalletInvestmentProgram model module.
* @module model/WalletInvestmentProgram
* @version v1
*/
export default class WalletInvestmentProgram {
    /**
    * Constructs a new <code>WalletInvestmentProgram</code>.
    * @alias module:model/WalletInvestmentProgram
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>WalletInvestmentProgram</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WalletInvestmentProgram} obj Optional instance to populate.
    * @return {module:model/WalletInvestmentProgram} The populated <code>WalletInvestmentProgram</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WalletInvestmentProgram();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} title
    */
    title = undefined;








}


