/**
 * Core API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoreApiV10);
  }
}(this, function(expect, CoreApiV10) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoreApiV10.BrokerAccountType();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BrokerAccountType', function() {
    it('should create an instance of BrokerAccountType', function() {
      // uncomment below and update the code to test BrokerAccountType
      //var instance = new CoreApiV10.BrokerAccountType();
      //expect(instance).to.be.a(CoreApiV10.BrokerAccountType);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CoreApiV10.BrokerAccountType();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new CoreApiV10.BrokerAccountType();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new CoreApiV10.BrokerAccountType();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new CoreApiV10.BrokerAccountType();
      //expect(instance).to.be();
    });

    it('should have the property leverages (base name: "leverages")', function() {
      // uncomment below and update the code to test the property leverages
      //var instance = new CoreApiV10.BrokerAccountType();
      //expect(instance).to.be();
    });

    it('should have the property currencies (base name: "currencies")', function() {
      // uncomment below and update the code to test the property currencies
      //var instance = new CoreApiV10.BrokerAccountType();
      //expect(instance).to.be();
    });

    it('should have the property minimumDepositsAmount (base name: "minimumDepositsAmount")', function() {
      // uncomment below and update the code to test the property minimumDepositsAmount
      //var instance = new CoreApiV10.BrokerAccountType();
      //expect(instance).to.be();
    });

    it('should have the property isForex (base name: "isForex")', function() {
      // uncomment below and update the code to test the property isForex
      //var instance = new CoreApiV10.BrokerAccountType();
      //expect(instance).to.be();
    });

    it('should have the property isSignalsAvailable (base name: "isSignalsAvailable")', function() {
      // uncomment below and update the code to test the property isSignalsAvailable
      //var instance = new CoreApiV10.BrokerAccountType();
      //expect(instance).to.be();
    });

  });

}));
