/**
 * Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoreApi);
  }
}(this, function(expect, CoreApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoreApi.ManagerAccountOnlineInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ManagerAccountOnlineInfo', function() {
    it('should create an instance of ManagerAccountOnlineInfo', function() {
      // uncomment below and update the code to test ManagerAccountOnlineInfo
      //var instane = new CoreApi.ManagerAccountOnlineInfo();
      //expect(instance).to.be.a(CoreApi.ManagerAccountOnlineInfo);
    });

    it('should have the property managerId (base name: "managerId")', function() {
      // uncomment below and update the code to test the property managerId
      //var instane = new CoreApi.ManagerAccountOnlineInfo();
      //expect(instance).to.be();
    });

    it('should have the property balance (base name: "balance")', function() {
      // uncomment below and update the code to test the property balance
      //var instane = new CoreApi.ManagerAccountOnlineInfo();
      //expect(instance).to.be();
    });

    it('should have the property equity (base name: "equity")', function() {
      // uncomment below and update the code to test the property equity
      //var instane = new CoreApi.ManagerAccountOnlineInfo();
      //expect(instance).to.be();
    });

  });

}));
